const scrollTypes = {
  UPDATE_Y_POSITION: "UPDATE_Y_POSITION",
  MAKE_WWD_VISIBLE: "MAKE_WWD_VISIBLE",
  MAKE_SS_VISIBLE: "MAKE_SS_VISIBLE",
  MAKE_AM_VISIBLE: "MAKE_AM_VISIBLE"
};

export default scrollTypes;
